#cloud-config

package_upgrade: true

packages:
  - apache2
  - ghostscript 
  - libapache2-mod-php 
  - mysql-client
  - php 
  - php-bcmath 
  - php-curl 
  - php-imagick 
  - php-intl 
  - php-json 
  - php-mbstring 
  - php-mysql 
  - php-xml 
  - php-zip


#/var/log/cloud-init-output.log